package com.example.ui.localization

import com.example.data.model.AppLanguage

object AppStrings {

    fun get(lang: AppLanguage, key: String): String {
        return when (lang) {
            AppLanguage.VIETNAMESE -> VI[key] ?: EN[key] ?: key
            AppLanguage.ENGLISH -> EN[key] ?: key
            AppLanguage.KHMER -> KM[key] ?: EN[key] ?: key
            AppLanguage.FRENCH -> FR[key] ?: EN[key] ?: key
        }
    }

    private val EN = mapOf(
        // App & Navigation
        "app_title" to "Ouk Chatrang",
        "app_subtitle" to "Ancient Khmer Chess",
        "angkor_era" to "Angkor · 802 AD",
        "welcome_greeting" to "Sursdey!",
        "welcome_tagline" to "I am Hanuman, your guide through the royal game of Angkor.",
        "choose_language" to "CHOOSE YOUR LANGUAGE",
        "enter" to "Chiến thôi!",
        "welcome_note" to "You can change the language later in Settings.",
        "home" to "Trang chủ",
        "flip_board" to "Flip Board",
        "new_game" to "New Game",
        "play" to "Play",
        "learn" to "Learn",
        "profile" to "Profile",
        "settings" to "Settings",

        // Header & Status
        "online_count" to "2,847 Online",
        "guest" to "Guest",
        "guest_mode" to "Guest Mode",
        "guest_stats_hidden" to "Sign in to track Elo & Rank",
        "sign_in_google" to "Sign in with Google",
        "sign_in_title" to "Google Account Sign In",
        "sign_in_desc" to "Sign in with Google to unlock Online Ranked matches, save your game history, and compete on the global leaderboard.",
        "sign_in_btn" to "Continue with Google",
        "sign_out" to "Sign Out",
        "logged_in_as" to "Logged in as",
        "account" to "Account",
        "sync_status" to "Cloud Sync Active",
        "guest_restriction_msg" to "Guest players can only play vs AI and Local 2-Player. Sign in with Google for full access.",

        // CTAs & Game Modes
        "quick_play_ai" to "Quick Play vs AI",
        "play_vs_ai" to "Play vs AI",
        "play_vs_ai_desc" to "4 Difficulty Tiers",
        "local_2p" to "Local 2 Player",
        "local_2p_desc" to "Pass & Play",
        "online_match" to "Online Match",
        "online_match_desc" to "Ranked Mode",
        "tactics_puzzles" to "Tactics Puzzles",
        "tactics_puzzles_desc" to "Daily Challenges",
        "history_replays" to "History & Replays",
        "history_replays_desc" to "Analyze Games",
        "leaderboard" to "Leaderboard",
        "leaderboard_desc" to "Top 100 Players",
        "custom_themes" to "Custom Themes",
        "custom_themes_desc" to "Angkor Stone, Royal Ivory, and Wooden Carvings",
        "pieces_guide" to "Pieces of Ouk Chatrang",
        "daily_wisdom" to "Daily Wisdom",
        "ranks" to "Ranks",

        // AI Setup Dialog
        "ai_setup_title" to "Play vs AI Engine",
        "choose_difficulty" to "CHOOSE DIFFICULTY",
        "play_as_side" to "PLAY AS SIDE",
        "white_side" to "⚪ White",
        "random_side" to "🎲 Random",
        "black_side" to "⚫ Black",
        "start_match" to "Start Match",
        "cancel" to "Cancel",

        // In-game Strings
        "white" to "White",
        "black" to "Black",
        "your_turn" to "Your Turn",
        "opponent_turn" to "Opponent's Turn...",
        "ai_thinking" to "AI Thinking...",
        "check" to "CHECK!",
        "checkmate" to "CHECKMATE!",
        "stalemate" to "STALEMATE (Draw)",
        "draw_by_count" to "DRAW BY COUNTING RULE",
        "white_wins" to "WHITE WINS!",
        "black_wins" to "BLACK WINS!",
        "game_drawn" to "MATCH DRAWN!",
        "resigned" to "Game ended by Resignation",
        "timeout" to "Game ended on Time",
        "undo" to "Undo",
        "hint" to "Hint",
        "chat" to "Chat",
        "draw_offer" to "Draw",
        "resign" to "Resign",
        "flip_board" to "Flip",
        "new_game" to "New Game",
        "rematch" to "Rematch",
        "return_home" to "Home",
        "moves_remaining" to "moves left",
        "counting_active" to "Counting Rule Active",
        "type_message" to "Type a message...",
        "send" to "Send",

        // Customization
        "board_theme" to "BOARD THEME",
        "piece_style" to "PIECE STYLE",
        "language_section" to "LANGUAGE",
        "preferences" to "PREFERENCES",
        "sound_effects" to "Sound Effects",
        "dark_mode" to "Dark Theme",
        "display_name" to "Display Name",
        "save" to "Save",
        "edit" to "Edit",

        // Leaderboard
        "global_rankings" to "Global Leaderboard",
        "global_rankings_desc" to "Top masters and grandmaster rankings",
        "tab_global" to "Global",
        "tab_weekly" to "Weekly",
        "tab_friends" to "Friends",

        // Tactics
        "tactics_title" to "Tactics & Lessons",
        "tactics_subtitle" to "Master authentic Ouk Chatrang rules & traps",
        "objective" to "Objective:",
        "next_lesson" to "Next Lesson",
        "lesson_complete" to "LESSON COMPLETED!",

        // Replay & History
        "match_history_title" to "Match History",
        "no_matches_yet" to "No matches played yet.",
        "replay_title" to "Match Replay",
        "last_move" to "Last move:",
        "start_pos" to "Starting position",
        "win" to "WIN",
        "loss" to "LOSS",
        "draw" to "DRAW",

        // Online Lobby
        "online_matchmaking" to "Online Matchmaking",
        "online_matchmaking_desc" to "Quick matchmaking & private friend rooms",
        "quick_match" to "Quick Match",
        "quick_match_desc" to "Instantly play against online opponents",
        "find_match" to "Find Match",
        "searching_opponent" to "Finding Opponent...",
        "searching_desc" to "Searching for players with similar Elo rating",
        "private_match" to "Private Match",
        "create_room_pin" to "Create Room PIN",
        "enter_pin" to "Enter 6-digit PIN",
        "join" to "Join",
        "waiting_friend" to "Waiting for friend to join...",

        // Move History & Audio
        "move_history" to "Move History",
        "review_mode" to "Reviewing Move",
        "resume_game" to "Resume Match",
        "start_move" to "Start",
        "current_move" to "Live",
        "bgm_music" to "Traditional Khmer Music",
        "sfx_volume" to "Sound Effects Volume",
        "music_volume" to "Music Volume",
        "audio_settings" to "Audio & Music Settings",
        "test_sound" to "Sound Check"
    )

    private val VI = mapOf(
        // App & Navigation
        "app_title" to "Cờ Ốc Khmer",
        "app_subtitle" to "Ouk Chatrang Truyền Thống",
        "angkor_era" to "Angkor · 802 AD",
        "welcome_greeting" to "Sursdey!",
        "welcome_tagline" to "Tôi là Hanuman, người dẫn đường cho bạn qua vương triều cờ Ốc Angkor.",
        "choose_language" to "CHỌN NGÔN NGỮ",
        "enter" to "Chiến thôi!",
        "welcome_note" to "Bạn có thể thay đổi ngôn ngữ sau trong Cài đặt.",
        "home" to "Trang chủ",
        "play" to "Chơi cờ",
        "learn" to "Học cờ",
        "profile" to "Hồ sơ",
        "settings" to "Cài đặt",

        // Header & Status
        "online_count" to "2,847 Đang online",
        "guest" to "Khách",
        "guest_mode" to "Chế độ Khách",
        "guest_stats_hidden" to "Đăng nhập để lưu Elo & Xếp hạng",
        "sign_in_google" to "Đăng nhập Gmail",
        "sign_in_title" to "Đăng Nhập Tài Khoản Google",
        "sign_in_desc" to "Đăng nhập bằng Google để mở khóa Đấu Xếp Hạng Trực Tuyến, lưu lịch sử ván đấu và tranh tài trên bảng xếp hạng toàn cầu.",
        "sign_in_btn" to "Tiếp tục với Google",
        "sign_out" to "Đăng xuất",
        "logged_in_as" to "Đã đăng nhập",
        "account" to "Tài khoản",
        "sync_status" to "Đồng bộ đám mây",
        "guest_restriction_msg" to "Tài khoản khách chỉ được chơi với Máy (AI) và 2 Người cục bộ. Vui lòng đăng nhập Google để mở khóa toàn bộ tính năng.",

        // CTAs & Game Modes
        "quick_play_ai" to "Chơi nhanh với AI",
        "play_vs_ai" to "Đấu với AI",
        "play_vs_ai_desc" to "4 Cấp độ thử thách",
        "local_2p" to "Chơi 2 người",
        "local_2p_desc" to "Đối kháng 1 thiết bị",
        "online_match" to "Đấu trực tuyến",
        "online_match_desc" to "Đấu Xếp Hạng",
        "tactics_puzzles" to "Câu đố chiến thuật",
        "tactics_puzzles_desc" to "Thử thách mỗi ngày",
        "history_replays" to "Lịch sử & Xem lại",
        "history_replays_desc" to "Phân tích ván đấu",
        "leaderboard" to "Bảng xếp hạng",
        "leaderboard_desc" to "Top 100 Kỳ thủ",
        "custom_themes" to "Giao diện bàn cờ",
        "custom_themes_desc" to "Đá Angkor, Ngà voi hoàng gia và Gỗ quý",
        "pieces_guide" to "Các Quân Cờ Ốc Khmer",
        "daily_wisdom" to "Lời Khuyên Kỳ Thủ",
        "ranks" to "Xếp hạng",

        // AI Setup Dialog
        "ai_setup_title" to "Thiết Lập Đấu Với Máy",
        "choose_difficulty" to "CHỌN CẤP ĐỘ AI",
        "play_as_side" to "CHỌN CẦM QUÂN",
        "white_side" to "⚪ Trắng (Đi trước)",
        "random_side" to "🎲 Ngẫu nhiên",
        "black_side" to "⚫ Đen (Đi sau)",
        "start_match" to "Bắt đầu ván đấu",
        "cancel" to "Hủy",

        // In-game Strings
        "white" to "Trắng",
        "black" to "Đen",
        "your_turn" to "Lượt của bạn",
        "opponent_turn" to "Lượt đối thủ...",
        "ai_thinking" to "Máy đang tính nước...",
        "check" to "CHIẾU TƯỚNG!",
        "checkmate" to "CHIẾU BÍ (Thắng)!",
        "stalemate" to "HÒA CỜ (Hết nước đi)",
        "draw_by_count" to "HÒA THEO LUẬT ĐẾM",
        "white_wins" to "BÊN TRẮNG THẮNG!",
        "black_wins" to "BÊN ĐEN THẮNG!",
        "game_drawn" to "TRẬN ĐẤU HÒA!",
        "resigned" to "Ván đấu kết thúc do xin thua",
        "timeout" to "Ván đấu kết thúc do hết giờ",
        "undo" to "Đi lại",
        "hint" to "Gợi ý",
        "chat" to "Trò chuyện",
        "draw_offer" to "Xin hòa",
        "resign" to "Xin thua",
        "flip_board" to "Xoay bàn",
        "new_game" to "Ván mới",
        "rematch" to "Đấu lại",
        "return_home" to "Trang chủ",
        "moves_remaining" to "nước còn lại",
        "counting_active" to "Đang đếm luật hòa",
        "type_message" to "Nhập tin nhắn...",
        "send" to "Gửi",

        // Customization
        "board_theme" to "GIAO DIỆN BÀN CỜ",
        "piece_style" to "KIỂU DÁNG QUÂN CỜ",
        "language_section" to "NGÔN NGỮ",
        "preferences" to "CÀI ĐẶT HỆ THỐNG",
        "sound_effects" to "Âm thanh nước đi",
        "dark_mode" to "Giao diện tối",
        "display_name" to "Tên hiển thị",
        "save" to "Lưu",
        "edit" to "Đổi",

        // Leaderboard
        "global_rankings" to "Bảng Xếp Hạng Toàn Cầu",
        "global_rankings_desc" to "Bảng vàng danh vọng và các Đại kiện tướng",
        "tab_global" to "Toàn cầu",
        "tab_weekly" to "Tuần này",
        "tab_friends" to "Bạn bè",

        // Tactics
        "tactics_title" to "Bài Học & Thế Cờ",
        "tactics_subtitle" to "Bí quyết cờ ốc Khmer truyền thống",
        "objective" to "Mục tiêu:",
        "next_lesson" to "Bài học tiếp theo",
        "lesson_complete" to "HOÀN THÀNH XUẤT SẮC!",

        // Replay & History
        "match_history_title" to "Lịch Sử Đấu",
        "no_matches_yet" to "Chưa có ván đấu nào được lưu.",
        "replay_title" to "Xem Lại Ván Đấu",
        "last_move" to "Nước vừa đi:",
        "start_pos" to "Thế cờ ban đầu",
        "win" to "THẮNG",
        "loss" to "THUA",
        "draw" to "HÒA",

        // Online Lobby
        "online_matchmaking" to "Đấu Trực Tuyến",
        "online_matchmaking_desc" to "Ghép trận nhanh & phòng đấu bạn bè",
        "quick_match" to "Ghép Trận Nhanh",
        "quick_match_desc" to "Tự động ghép với kỳ thủ có cùng điểm Elo",
        "find_match" to "Tìm trận đấu",
        "searching_opponent" to "Đang tìm đối thủ...",
        "searching_desc" to "Kết nối máy chủ khu vực Đông Nam Á",
        "private_match" to "Phòng Riêng",
        "create_room_pin" to "Tạo mã phòng PIN",
        "enter_pin" to "Nhập mã 6 chữ số",
        "join" to "Vào phòng",
        "waiting_friend" to "Đang đợi bạn bè tham gia...",

        // Move History & Audio
        "move_history" to "Lịch sử nước đi",
        "review_mode" to "Đang xem lại nước đi",
        "resume_game" to "Tiếp tục ván cờ",
        "start_move" to "Bắt đầu",
        "current_move" to "Hiện tại",
        "bgm_music" to "Nhạc nền truyền thống Khmer",
        "sfx_volume" to "Âm lượng hiệu ứng",
        "music_volume" to "Âm lượng nhạc nền",
        "audio_settings" to "Cài đặt Âm thanh & Âm nhạc",
        "test_sound" to "Thử âm thanh"
    )

    private val KM = mapOf(
        // App & Navigation
        "app_title" to "អុកចត្រង្គ",
        "app_subtitle" to "អុកបុរាណខ្មែរ",
        "angkor_era" to "Angkor · 802 AD",
        "welcome_greeting" to "សួស្តី!",
        "welcome_tagline" to "ខ្ញុំគឺហនុមាន នឹងនាំអ្នកទៅកាន់ល្បែងព្រះរាជានៃអង្គរ។",
        "choose_language" to "ជ្រើសរើសភាសា",
        "enter" to "Chiến thôi!",
        "welcome_note" to "អ្នកអាចប្តូរភាសានៅពេលក្រោយក្នុងការកំណត់។",
        "home" to "ទំព័រដើម",
        "flip_board" to "បង្វិលក្តារ",
        "new_game" to "ហ្គេមថ្មី",
        "play" to "លេង",
        "learn" to "រៀន",
        "profile" to "គណនី",
        "settings" to "ការកំណត់",

        // Header & Status
        "online_count" to "២,៨៤៧ លើបណ្ដាញ",
        "guest" to "ភ្ញៀវ",
        "guest_mode" to "របៀបភ្ញៀវ",
        "guest_stats_hidden" to "ចូលគណនីដើម្បីរក្សាពិន្ទុ Elo",
        "sign_in_google" to "ចូលតាម Google",
        "sign_in_title" to "ចូលគណនី Google",
        "sign_in_desc" to "ចូលតាម Google ដើម្បីលេងប្រកួតតាមអ៊ីនធឺណិត និងរក្សាទុកកំណត់ត្រាប្រកួត។",
        "sign_in_btn" to "បន្តជាមួយ Google",
        "sign_out" to "ចាកចេញ",
        "logged_in_as" to "បានចូលជា",
        "account" to "គណនី",
        "sync_status" to "បានធ្វើសមកាលកម្ម",
        "guest_restriction_msg" to "ភ្ញៀវអាចលេងបានតែជាមួយ AI និងលេង ២ នាក់ផ្ទាល់ប៉ុណ្ណោះ។ សូមចូលគណនី Google ដើម្បីលេងពេញលេញ។",

        // CTAs & Game Modes
        "quick_play_ai" to "លេងរហ័សជាមួយ AI",
        "play_vs_ai" to "លេងជាមួយ AI",
        "play_vs_ai_desc" to "៤ កម្រិតពិបាក",
        "local_2p" to "លេង ២ នាក់",
        "local_2p_desc" to "លេងលើទូរស័ព្ទតែមួយ",
        "online_match" to "ប្រកួតតាមអនឡាញ",
        "online_match_desc" to "របៀបចំណាត់ថ្នាក់",
        "tactics_puzzles" to "លំហាត់យុទ្ធសាស្ត្រ",
        "tactics_puzzles_desc" to "ការប្រកួតប្រជែងប្រចាំថ្ងៃ",
        "history_replays" to "ប្រវត្តិ & ការមើលឡើងវិញ",
        "history_replays_desc" to "វិភាគការប្រកួត",
        "leaderboard" to "តារាងពិន្ទុ",
        "leaderboard_desc" to "កីឡាករកំពូល ១០០ នាក់",
        "custom_themes" to "ស្បែកក្តារអុក",
        "custom_themes_desc" to "ថ្មអង្គរ ភ្លុកដំរី និងឈើប្រណិត",
        "pieces_guide" to "គ្រាប់អុកចត្រង្គ",
        "daily_wisdom" to "ដំបូន្មានប្រចាំថ្ងៃ",
        "ranks" to "ចំណាត់ថ្នាក់",

        // AI Setup Dialog
        "ai_setup_title" to "កំណត់ការលេងជាមួយ AI",
        "choose_difficulty" to "ជ្រើសរើសកម្រិត",
        "play_as_side" to "ជ្រើសរើសខាង",
        "white_side" to "⚪ ស (ដើរមុន)",
        "random_side" to "🎲 ចៃដន្យ",
        "black_side" to "⚫ ខ្មៅ (ដើរក្រោយ)",
        "start_match" to "ចាប់ផ្តើមការប្រកួត",
        "cancel" to "បោះបង់",

        // In-game Strings
        "white" to "ស",
        "black" to "ខ្មៅ",
        "your_turn" to "វេនរបស់អ្នក",
        "opponent_turn" to "វេនគូប្រកួត...",
        "ai_thinking" to "AI កំពុងគិត...",
        "check" to "អុក!",
        "checkmate" to "អុកស្លាប់!",
        "stalemate" to "ស្មើ (ទាល់ក្រឡា)",
        "draw_by_count" to "ស្មើតាមច្បាប់រាប់",
        "white_wins" to "ខាងសឈ្នះ!",
        "black_wins" to "ខាងខ្មៅឈ្នះ!",
        "game_drawn" to "ការប្រកួតស្មើគ្នា!",
        "resigned" to "ចុះចាញ់",
        "timeout" to "អស់ម៉ោង",
        "undo" to "ថយក្រោយ",
        "hint" to "ជំនួយ",
        "chat" to "ជជែក",
        "draw_offer" to "សុំស្មើ",
        "resign" to "ចុះចាញ់",
        "flip_board" to "បង្វិលក្តារ",
        "new_game" to "ល្បែងថ្មី",
        "rematch" to "លេងម្តងទៀត",
        "return_home" to "ទំព័រដើម",
        "moves_remaining" to "ក្រឡានៅសល់",
        "counting_active" to "ច្បាប់រាប់កំពុងដំណើរការ",
        "type_message" to "សរសេរសារ...",
        "send" to "ផ្ញើ",

        // Customization
        "board_theme" to "ស្បែកក្តារអុក",
        "piece_style" to "រចនាប័ទ្មគ្រាប់អុក",
        "language_section" to "ភាសា",
        "preferences" to "ការកំណត់",
        "sound_effects" to "សំឡេងដើរគ្រាប់",
        "dark_mode" to "ស្បែកងងឹត",
        "display_name" to "ឈ្មោះកីឡាករ",
        "save" to "រក្សាទុក",
        "edit" to "កែប្រែ",

        // Leaderboard
        "global_rankings" to "តារាងពិន្ទុសកល",
        "global_rankings_desc" to "កំពូលកីឡាករអុកចត្រង្គ",
        "tab_global" to "សកល",
        "tab_weekly" to "ប្រចាំសប្តាហ៍",
        "tab_friends" to "មិត្តភក្តិ",

        // Tactics
        "tactics_title" to "យុទ្ធសាស្ត្រ & មេរៀន",
        "tactics_subtitle" to "រៀនក្បួនអុកចត្រង្គបុរាណខ្មែរ",
        "objective" to "គោលបំណង:",
        "next_lesson" to "មេរៀនបន្ទាប់",
        "lesson_complete" to "បានបញ្ចប់មេរៀន!",

        // Replay & History
        "match_history_title" to "ប្រវត្តិប្រកួត",
        "no_matches_yet" to "មិនទាន់មានការប្រកួតនៅឡើយទេ",
        "replay_title" to "មើលការប្រកួតឡើងវិញ",
        "last_move" to "ក្រឡាចុងក្រោយ:",
        "start_pos" to "ទីតាំងដើម",
        "win" to "ឈ្នះ",
        "loss" to "ចាញ់",
        "draw" to "ស្មើ",

        // Online Lobby
        "online_matchmaking" to "ប្រកួតតាមអនឡាញ",
        "online_matchmaking_desc" to "ស្វែងរកគូប្រកួតរហ័ស & បន្ទប់ឯកជន",
        "quick_match" to "ស្វែងរកគូប្រកួតរហ័ស",
        "quick_match_desc" to "ផ្គូផ្គងជាមួយកីឡាករមានពិន្ទុស្មើគ្នា",
        "find_match" to "ស្វែងរក",
        "searching_opponent" to "កំពុងស្វែងរកគូប្រកួត...",
        "searching_desc" to "កំពុងតភ្ជាប់ទៅកាន់ម៉ាស៊ីនមេ",
        "private_match" to "បន្ទប់ឯកជន",
        "create_room_pin" to "បង្កើតកូដ PIN",
        "enter_pin" to "បញ្ចូលលេខកូដ ៦ ខ្ទង់",
        "join" to "ចូលរួម",
        "waiting_friend" to "កំពុងរង់ចាំមិត្តភក្តិចូលរួម...",

        // Move History & Audio
        "move_history" to "ប្រវត្តិនៃការដើរ",
        "review_mode" to "កំពុងពិនិត្យមើលទឹកដើរ",
        "resume_game" to "បន្តការប្រកួត",
        "start_move" to "ដើម",
        "current_move" to "បច្ចុប្បន្ន",
        "bgm_music" to "តន្ត្រីប្រពៃណីខ្មែរ",
        "sfx_volume" to "កម្រិតសំឡេងបែបផែន",
        "music_volume" to "កម្រិតសំឡេងតន្ត្រី",
        "audio_settings" to "ការកំណត់សំឡេង & តន្ត្រី",
        "test_sound" to "សាកល្បងសំឡេង"
    )

    private val FR = mapOf(
        // App & Navigation
        "app_title" to "Ouk Chatrang",
        "app_subtitle" to "Échecs Traditionnels Khmers",
        "angkor_era" to "Angkor · 802 AD",
        "welcome_greeting" to "Bonjour !",
        "welcome_tagline" to "Je suis Hanuman, votre guide dans le jeu royal d'Angkor.",
        "choose_language" to "CHOISISSEZ VOTRE LANGUE",
        "enter" to "Chiến thôi!",
        "welcome_note" to "Vous pourrez changer la langue plus tard dans les réglages.",
        "home" to "Accueil",
        "flip_board" to "Tourner",
        "new_game" to "Nouveau",
        "play" to "Jouer",
        "learn" to "Apprendre",
        "profile" to "Profil",
        "settings" to "Paramètres",

        // Header & Status
        "online_count" to "2 847 En ligne",
        "guest" to "Invité",
        "guest_mode" to "Mode Invité",
        "guest_stats_hidden" to "Connectez-vous pour enregistrer l'Elo",
        "sign_in_google" to "Connexion Google",
        "sign_in_title" to "Connexion avec Google",
        "sign_in_desc" to "Connectez-vous pour débloquer les matchs classés en ligne et enregistrer votre progression.",
        "sign_in_btn" to "Continuer avec Google",
        "sign_out" to "Se déconnecter",
        "logged_in_as" to "Connecté en tant que",
        "account" to "Compte",
        "sync_status" to "Synchronisation cloud active",
        "guest_restriction_msg" to "Les invités ne peuvent jouer que contre l'IA et en local. Connectez-vous avec Google pour l'accès complet.",

        // CTAs & Game Modes
        "quick_play_ai" to "Partie Rapide vs IA",
        "play_vs_ai" to "Jouer contre l'IA",
        "play_vs_ai_desc" to "4 Niveaux de Difficulté",
        "local_2p" to "2 Joueurs Local",
        "local_2p_desc" to "Sur le même écran",
        "online_match" to "Match en Ligne",
        "online_match_desc" to "Mode Classé",
        "tactics_puzzles" to "Puzzles Tactiques",
        "tactics_puzzles_desc" to "Défis Quotidiens",
        "history_replays" to "Historique & Replays",
        "history_replays_desc" to "Analyser les Parties",
        "leaderboard" to "Classement",
        "leaderboard_desc" to "Top 100 Joueurs",
        "custom_themes" to "Thèmes Personnalisés",
        "custom_themes_desc" to "Pierre d'Angkor, Ivoire Royal et Bois Sculpté",
        "pieces_guide" to "Pièces d'Ouk Chatrang",
        "daily_wisdom" to "Sagesse Quotidienne",
        "ranks" to "Rangs",

        // AI Setup Dialog
        "ai_setup_title" to "Configurer la partie contre l'IA",
        "choose_difficulty" to "CHOISIR LA DIFFICULTÉ",
        "play_as_side" to "JOUER AVEC LES",
        "white_side" to "⚪ Blancs",
        "random_side" to "🎲 Aléatoire",
        "black_side" to "⚫ Noirs",
        "start_match" to "Commencer la Partie",
        "cancel" to "Annuler",

        // In-game Strings
        "white" to "Blancs",
        "black" to "Noirs",
        "your_turn" to "À votre tour",
        "opponent_turn" to "Tour de l'adversaire...",
        "ai_thinking" to "L'IA réfléchit...",
        "check" to "ÉCHEC!",
        "checkmate" to "ÉCHEC ET MAT!",
        "stalemate" to "PAT (Match Nul)",
        "draw_by_count" to "NUL PAR RÈGLE DE COMPTAGE",
        "white_wins" to "LES BLANCS GAGNENT!",
        "black_wins" to "LES NOIRS GAGNENT!",
        "game_drawn" to "PARTIE NULLE!",
        "resigned" to "Partie terminée par abandon",
        "timeout" to "Partie terminée au temps",
        "undo" to "Annuler",
        "hint" to "Indice",
        "chat" to "Chat",
        "draw_offer" to "Nul",
        "resign" to "Abandonner",
        "flip_board" to "Pivoter",
        "new_game" to "Nouvelle Partie",
        "rematch" to "Revanche",
        "return_home" to "Accueil",
        "moves_remaining" to "coups restants",
        "counting_active" to "Règle de comptage active",
        "type_message" to "Écrivez un message...",
        "send" to "Envoyer",

        // Customization
        "board_theme" to "THÈME DE L'ÉCHIQUIER",
        "piece_style" to "STYLE DES PIÈCES",
        "language_section" to "LANGUE",
        "preferences" to "PRÉFÉRENCES",
        "sound_effects" to "Effets sonores",
        "dark_mode" to "Thème sombre",
        "display_name" to "Nom d'affichage",
        "save" to "Sauvegarder",
        "edit" to "Modifier",

        // Leaderboard
        "global_rankings" to "Classement Mondial",
        "global_rankings_desc" to "Top des grands maîtres",
        "tab_global" to "Mondial",
        "tab_weekly" to "Hebdomadaire",
        "tab_friends" to "Amis",

        // Tactics
        "tactics_title" to "Tactiques & Leçons",
        "tactics_subtitle" to "Maîtrisez les règles traditionnelles",
        "objective" to "Objectif :",
        "next_lesson" to "Leçon Suivante",
        "lesson_complete" to "LEÇON TERMINÉE!",

        // Replay & History
        "match_history_title" to "Historique des Matchs",
        "no_matches_yet" to "Aucune partie enregistrée.",
        "replay_title" to "Revoir la Partie",
        "last_move" to "Dernier coup :",
        "start_pos" to "Position initiale",
        "win" to "VICTOIRE",
        "loss" to "DÉFAITE",
        "draw" to "NUL",

        // Online Lobby
        "online_matchmaking" to "Matchmaking en Ligne",
        "online_matchmaking_desc" to "Match rapide et salons privés",
        "quick_match" to "Match Rapide",
        "quick_match_desc" to "Jouez instantanément contre un adversaire",
        "find_match" to "Trouver un match",
        "searching_opponent" to "Recherche d'un adversaire...",
        "searching_desc" to "Connexion au serveur...",
        "private_match" to "Salon Privé",
        "create_room_pin" to "Créer un code PIN",
        "enter_pin" to "Code PIN à 6 chiffres",
        "join" to "Rejoindre",
        "waiting_friend" to "En attente d'un ami...",

        // Move History & Audio
        "move_history" to "Historique des coups",
        "review_mode" to "Mode révision",
        "resume_game" to "Reprendre la partie",
        "start_move" to "Début",
        "current_move" to "Actuel",
        "bgm_music" to "Musique traditionnelle khmère",
        "sfx_volume" to "Volume des effets",
        "music_volume" to "Volume de la musique",
        "audio_settings" to "Paramètres audio & musique",
        "test_sound" to "Tester les sons"
    )
}
